### ISSUE TITLE
Slack is deprecating older API methods

### ISSUE THREAD

**Issue by robincornett** [easydigitaldownloads/edd-slack#120]
Just saw this [announcement from Gravity Forms](https://docs.gravityforms.com/slack-update-for-new-api/) and looked to see if this extension is affected as well. I see at least one deprecated method call:

* https://github.com/easydigitaldownloads/edd-slack/blob/master/core/ssl-only/slack-invites/class-edd-slack-app-invites-settings.php#L146

I'm not seeing any others, so maybe it's just the one.

**Comment by ashleyfae** [comment]
https://api.slack.com/changelog/2020-01-deprecating-antecedents-to-the-conversations-api
