### ISSUE TITLE
REST API: register_rest_route called incorrectly

### ISSUE THREAD

**Issue by robincornett** [easydigitaldownloads/edd-slack#148]
I expect to not have PHP notices when I'm editing a post in the block editor, but with Slack active, I get:

> PHP Notice:  register_rest_route was called <strong>incorrectly</strong>. The REST API route definition for <code>edd-slack/v1/slack-app/interactive-message/submit</code> is missing the required <code>permission_callback</code> argument. For REST API routes that are intended to be public, use <code>__return_true</code> as the permission callback. Please see <a href="https://wordpress.org/support/article/debugging-in-wordpress/">Debugging in WordPress</a> for more information. (This message was added in version 5.5.0.)
> PHP Notice:  register_rest_route was called <strong>incorrectly</strong>. The REST API route definition for <code>edd-slack/v1/slack-app/slash-command/submit</code> is missing the required <code>permission_callback</code> argument. For REST API routes that are intended to be public, use <code>__return_true</code> as the permission callback. Please see <a href="https://wordpress.org/support/article/debugging-in-wordpress/">Debugging in WordPress</a> for more information. (This message was added in version 5.5.0.)

**Comment by ashleyfae** [comment]
Looks like `__return_true` is indeed applicable here.

**Comment by ashleyfae** [comment]
API endpoints are registered here: https://github.com/easydigitaldownloads/edd-slack/blob/df85be1cb5596e0fd796dce3d5bb44a9fe88c307/core/ssl-only/class-edd-slack-ssl-rest.php#L37-L47

**Comment by rwebster85** [comment]
I wasn't able to reproduce the error notice, although it could just be my setup. The arguments have been set accordingly though.

**Comment by ashleyfae** [comment]
> I wasn't able to reproduce the error notice, although it could just be my setup. The arguments have been set accordingly though.

The endpoints are only registered if you're using SSL and have authenticated with Slack, so if you haven't done either of those then you won't get the errors because the endpoints won't actually be loading.
