### ISSUE TITLE
Single Slash Protocol in %active_site%

### ISSUE THREAD

**Issue by d4mation** [easydigitaldownloads/edd-slack#63]
I'm adding the Protocol very similar to how EDD Software Licenses does it.

https://github.com/realbigplugins/edd-slack/blob/0facec951df7fa75a432c8b05f55b1ed1bb368d5/core/integrations/edd-software-licensing/class-edd-slack-software-licensing.php#L320-L323

Somehow this invalid URL got fed into `$_GET['url']`.

```
Josh Nelson Has Activated a License for LearnDash – Gradebook
License Key Activated
Josh Nelson is now using 1 out of 1 activations for their License Key.

They activated this License Key on <http:/etudiants.institutbibliquelogos.com|http:/etudiants.institutbibliquelogos.com> and it expires on April 24, 2018.

View this License
```

**Comment by cklosowski** [comment]
I believe I've fixed this in #110
